/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './*.html',
    'digiland/**/*.html',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#42474f',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#9ccaff',
        'on-background': '#191c1e',
        'on-primary-container': '#87baf3',
        'surface-container-highest': '#e2e2e4',
        'primary': '#003358',
        'background': '#f9f9fb',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#005149',
        'inverse-primary': '#9ccaff',
        'on-error-container': '#93000a',
        'surface-container-low': '#f3f3f6',
        'error': '#ba1a1a',
        'primary-container': '#004a7c',
        'on-tertiary-fixed-variant': '#005048',
        'on-secondary-fixed-variant': '#004f54',
        'surface-container': '#edeef0',
        'inverse-on-surface': '#f0f1f3',
        'surface-container-high': '#e7e8ea',
        'tertiary-fixed-dim': '#8ad4c8',
        'surface-bright': '#f9f9fb',
        'secondary': '#006970',
        'surface-dim': '#d9dadc',
        'surface-variant': '#e2e2e4',
        'tertiary': '#003832',
        'inverse-surface': '#2e3132',
        'secondary-fixed-dim': '#85d3db',
        'surface-tint': '#296195',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#002022',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#7ac3b8',
        'secondary-container': '#9eedf4',
        'secondary-fixed': '#a1eff7',
        'on-tertiary-fixed': '#00201c',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#a6f1e4',
        'surface': '#f9f9fb',
        'error-container': '#ffdad6',
        'outline-variant': '#c1c7d0',
        'on-surface': '#191c1e',
        'on-primary-fixed': '#001d35',
        'on-secondary-container': '#0c6d74',
        'primary-fixed': '#d0e4ff',
        'outline': '#727780',
        'on-primary-fixed-variant': '#00497b',
      },
      fontFamily: {
        headline: ['Public Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontSize: {
        md: ['1.25rem', { lineHeight: '1.75rem' }],
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(135deg, #003358 0%, #004a7c 100%)',
        'primary-gradient': 'linear-gradient(135deg, #003358 0%, #004a7c 100%)',
        'institutional-gradient': 'linear-gradient(135deg, #003358 0%, #006970 100%)',
      },
      animation: {
        'pulse-slow': 'pulse-slow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.5' },
        },
      },
    },
  },
  plugins: [],
};
